package runereader.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;

import java.util.List;

@Getter
@JsonIgnoreProperties(
        {"command",
        "ret_code",
        "wizard_info",
        "scenario_list",
        "defense_unit_list",
        "server_arena_defense_unit_list",
        "quest_active",
        "quest_rewarded",
        "event_id_list",
        "building_list",
        "deco_list",
        "obstacle_list",
        "mob_list",
        "mob_costume_equip_list",
        "mob_costume_part_list",
        "object_state",
        "object_storage_list",
        "homunculus_skill_list",
        "unit_list",
        "unit_collection",
        "{50}",
        "{19}",
        "{16}",
        "{14}",
        "{11}",
        "{8}",
        "{7}",
        "{6}",
        "{5}",
        "{4}",
        "{3}",
        "{2}",
        "{1}",
        "island_info",
        "inventory_info",
        "inventory_open_info",
        "inventory_mail_info",
        "emoticon_favorites",
        "rune_craft_item_list",
        "artifacts",
        "artifact_crafts",
        "markers",
        "period_item_list",
        "notice_info",
        "push_noti_status: 0",
        "guildsiege_defense_unit_list",
        "unit_lock_list",
        "rune_lock_list",
        "invite_counter_list",
        "shop_daily_bonus_list",
        "deck_list",
        "deck_recent_list",
        "rtpvp_selected_npc_list",
        "shop_bonus_event",
        "lobby_proud_unit_id_list",
        "summon_choices",
        "item_cart_prev_reset_timestamp: 1681534800",
        "item_cart_next_reset_timestamp: 1682892000",
        "unit_state",
        "beginner_summon_free",
        "world_arena_rune_equip_list",
        "world_arena_rune_equip_sync: 1",
        "world_arena_artifact_equip_sync: true",
        "world_arena_artifact_equip_list",
        "world_arena_favorite_unit_id_list",
        "raid_best_clear_info_list",
        "battle_option_list",
        "friend_list",
        "helper_list",
        "helper_remained: 80477",
        "mentor_helper_list",
        "mentee_slot_list",
        "mentor_slot_list",
        "daily_reward_inactive_status: 0",
        "daily_reward_new_user_status: 0",
        "daily_reward_special_status: 0",
        "daily_reward_special_pass_status: 0",
        "pvp_reward_list",
        "play_start_timestamp: 1477384571",
        "is_dungeon_open_check_user: false",
        "worldboss_used_unit",
        "world_boss_best_rank_id: 12",
        "costume_ticket_purchased_list",
        "session_key: bd71928f0e04122e10c3a4ffeffe08c97dd3ba20",
        "raid_info_list",
        "summon_special_info",
        "wish_list",
        "friend_list",
        "battle_option_list",
        "user_reference_date_info",
        "raid_best_clear_info_list",
        })
public class Runes {

    @JsonProperty("runes")
    private List<Rune> runeArray;

}


